export const begin = "var onLoginRequest = function(context){executeStep(1);}"
export const loginRequest = "onLoginRequest"
export const stepExecutor = "executeStep"
export const onSuccess = "onSuccess"
export const onFail = "onFailure"
export const context = "context"
export const variable = "var"
export const roles = "rolesToStepUp"
export const hasRoles = "hasAnyOfTheRoles"
export const user = "user"
export const currentKnownSubject = "currentKnownSubject"
