export const SAVE_AST = "SAVE_AST";
export const SAVE_AST_FROM_VISUAL_EDITOR = "SAVE_AST_FROM_VISUAL_EDITOR";
export const ADD_FACTOR_TO_STEP = "ADD_FACTOR_TO_STEP";
export const SHIFT_ADD_FACTORS_TO_STEP = "SHIFT_ADD_FACTORS_TO_STEP";
export const CHANGE_SUBJECT_FROM_STEP = "CHANGE_SUBJECT_FROM_STEP";
export const CHANGE_ATTRIBUTES_FROM_STEP = "CHANGE_ATTRIBUTES_FROM_STEP";

